// react/jwt-demo/src/views/Login/index.jsx
import {
    useRef
} from 'react';
import {
    useUserStore
} from '../../store/user'
import {
    useNavigate
} from 'react-router-dom'

const Login = () => {
    const usernameRef = useRef();
    const passwordRef = useRef();
    const {login} = useUserStore();
    const navigate = useNavigate();
    const handleLogin = (e) => {
        e.preventDefault();
        const username = usernameRef.current.value;
        const password = passwordRef.current.value;
        if(!username || !password){
            alert('请输入用户名或密码');
            return;
        }
        login({username,password});
        setTimeout(()=>{
            navigate('/');
        },1000)
    }
    return (
        <>
            <form onSubmit={handleLogin}>
                <div>
                    <label htmlFor="username">Username</label>
                    <input 
                        type="text" 
                        id="username" 
                        ref={usernameRef} 
                        placeholder="请输入用户名"
                        required
                    />
                </div>
                <div>
                    <label htmlFor="password">Password</label>
                    <input 
                        type="password" 
                        id="password" 
                        ref={passwordRef} 
                        placeholder="请输入密码"
                        required
                    />
                </div>
                <div>
                    <button type="submit">Login</button>
                </div>
            </form>
        </>
    )
}
export default Login;

// vue/vue-login/src/views/Login.vue
<template>
    <div className="login-container">
      <h2>登录</h2>
      <form @submit.prevent="handleLogin">
        <input type="text" placeholder="用户名" required  v-model="username"/>
        <input type="password" placeholder="密码" required  v-model="password"/>
        <button type="submit">登录</button>
      </form>
    </div>
  </template>
  <script lang="ts" setup>
  import { ref } from 'vue';
  import { useUserStore } from '@/store/user';
  import { login } from '@/api/login';
  import { useRouter } from 'vue-router'
  
  const username = ref("");
  const password = ref("");
  const userStore = useUserStore();
  const router = useRouter();
  
  const handleLogin = async () => {
    try {
      const data = await login({
        username: username.value,
        password: password.value
      })
      console.log(data);
      userStore.setToken(data.token);
      userStore.setUsername(data.username);
      router.push('/')
  
    } catch(err) {
      console.error(err)
    }
  }
  
  
  
  </script>
