// vue/vue-login/src/views/Login.vue
<template>
    <div className="login-container">
      <h2>登录</h2>
      <form @submit.prevent="handleLogin">
        <input type="text" placeholder="用户名" required  v-model="username"/>
        <input type="password" placeholder="密码" required  v-model="password"/>
        <button type="submit">登录</button>
      </form>
    </div>
  </template>
  <script lang="ts" setup>
  import { ref } from 'vue';
  import { useUserStore } from '@/store/user';
  import { login } from '@/api/login';
  import { useRouter } from 'vue-router'
  
  const username = ref("");
  const password = ref("");
  const userStore = useUserStore();
  const router = useRouter();
  
  const handleLogin = async () => {
    try {
      const data = await login({
        username: username.value,
        password: password.value
      })
      console.log(data);
      userStore.setToken(data.token);
      userStore.setUsername(data.username);
      router.push('/')
  
    } catch(err) {
      console.error(err)
    }
  }
  
  
  
  </script>

// react/deep-router/src/pages/Login/index.jsx
import { useState } from "react";
import { 
    useNavigate,// Navigate 组件 js 跳转
    useLocation

} from "react-router-dom";

const Login = () =>{
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const location = useLocation();
    // console.log(location.state.from);
    const navigate = useNavigate();// navigate 能力
    

    const handleSubmit = (event) =>{
        event.preventDefault();
       // console.log(username, password);
       if(username === 'admin' && password === '123456'){
        localStorage.setItem('isLogin', 'true');
        navigate(location.state.from || '/');
       }else{
        alert('用户名或密码错误');
       }
    }

    return (
        <form onSubmit={handleSubmit}>

            <h1>Login</h1>
            <input 
            type="text" 
            placeholder="username" 
            required
            value={username}
            onChange={(event)=>setUsername(event.target.value)}
            />
            <input 
            type="password" 
            placeholder="password" 
            required
            value={password}
            onChange={(event)=>setPassword(event.target.value)}
            />
            <button type="submit">Login</button>
        </form>
    )
}

export default Login;
